# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db36df40a126d2ead917dccf5ee2ad361f1f86c37930cad1e6c000d749f04e899ba345cdbfa38198fe09bef84a06c89fec2a66afe0b1235b36d7045d1bb0df75

test:
  secret_key_base: 32d916a548fc706782ba54329699a81f6ed46bb7cd0dc5c6b1879513f3ede747e0289cfb3a81ec246f6ecc3ca051cddb99e30cd8fdce6216b787ec90ae8178ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
